bugfix: import time function instead of time module Summary:
error message:

Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train(epoch)
  File "train.py", line 30, in train
    start = time.time()
AttributeError: 'builtin_function_or_method' object has no attribute 'time'