fix: integer division error in shufflenetv2
Details:
Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Error occurs, No graph saved
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    writer.add_graph(net, input_tensor)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 714, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 291, in graph
    raise e
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 1109, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, strict, _force_outplace)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/by/pytorch-cifar100/models/shufflenetv2.py", line 133, in forward
    x = self.stage2(x)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/by/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/by/pytorch-cifar100/models/shufflenetv2.py", line 96, in forward
    x = channel_shuffle(x, 2)
  File "/home/by/pytorch-cifar100/models/shufflenetv2.py", line 33, in channel_shuffle
    channels_per_group = int(channels / groups)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.